### ISSUE TITLE
ExpiringValue caches failures

### ISSUE THREAD

**Issue by kernwig** [rackspace/sailplane#146]
When the factory function for `ExpiringValue` throws (aka: returns a rejected Promise), that failure is cached.

I want to not cache failures and instead retry on the next `get()` call.

**Comment by kernwig** [comment]
Released in expiring-value@4.0.0

**Comment by kernwig** [comment]
Reopening:

When used elsewhere and testing case of factory returning an thrown error, an unhandled exception failure causes the test to fail. This can be reproduced in the library's unit tests simply by removing `NODE_OPTIONS=--unhandled-rejections=none` from the `jest` script:

```
 RUNS  lib/expiring-value.test.ts
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 
    at Object.<anonymous> (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/lib/expiring-value.test.ts:69:63)
    at Promise.then.completed (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-circus/build/run.js:121:9)
    at run (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/adamfanello/dev/onica/oss/sailplane/expiring-value/node_modules/jest-runner/build/runTest.js:444:34)

```
